version: '3.3'

services:
  githubactionstest:
    build: .
    container_name: web
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - data-volume:/dianabustos/media
      - .:/dianabustos

  db:
    image: postgres:11.8
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - db-volume:/var/lib/postgresql/data

volumes:
  data-volume:
  db-volume:
