name: Django Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pwd
          pip install -r requirements.txt
      - name: Django Testing project
        run: |
          python3 manage.py test # Don't forget to run tests
