name: Django Workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:11.8
        env:
          POSTGRES_USER: test_actions
          POSTGRES_PASSWORD: TestActions123
          POSTGRES_DB: test_actions
          POSTGRES_PORT: 5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pwd
          pip install -r requirements.txt
      - name: Django Testing project
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: test_actions
          POSTGRES_PASSWORD: TestActions123
          POSTGRES_DB: test_actions
          POSTGRES_PORT: 5432
        run: |
          python3 manage.py test # Don't forget to run tests
